language: node_js
node_js:
  - '4'
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - echo "//npme.eocng.org/:_authToken=$NPM_TOKEN" >> .npmrc
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    # ignore git tags created by semantic-release, like "v1.2.3"
    - /^v\d+\.\d+\.\d+$/
